# Generated by Django 5.1.5 on 2025-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("chat_history", models.JSONField(blank=True, default=list)),
                ("state", models.CharField(default="start", max_length=20)),
                ("mistake_count", models.IntegerField()),
                (
                    "selected_language",
                    models.CharField(default="Unknown", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
